---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-clusterrole
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics # access /metrics/resource
  - nodes/proxy # access /pods
  - nodes/stats # access /pods
  verbs:
  - 'get'
  - 'watch'
  - 'list'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-clusterrole-binding
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-clusterrole
  apiGroup: "rbac.authorization.k8s.io"
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
