---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kepler.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kepler.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "kepler.selectorLabels" . | nindent 4 }}
