name: Integration test

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  integration_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chart/kepler
    strategy:
      matrix:
        cluster_provider: [kind, microshift]
    steps:
      - uses: actions/checkout@v4

      - name: use kepler action for kind cluster build
        uses: sustainable-computing-io/kepler-action@v0.0.5
        with:
          ebpfprovider: libbpf
          cluster_provider: ${{matrix.cluster_provider}}

      - name: install helm
        uses: azure/setup-helm@v4.1.0

      - name: helm lint
        run: |
            helm lint . --debug

      - name: deploy kepler using helm chart
        run: |
            tree -a
            kubectl get pods 
            helm install kepler . --values values.yaml --create-namespace --namespace kepler --dry-run --debug
            helm install kepler . --values values.yaml --create-namespace --namespace kepler --debug

      - name: test if kepler is alive
        run: |
          sleep 60
          kubectl logs $(kubectl -n kepler get pods -oname) -n kepler
          kubectl get all -n kepler
