name: Integration test

on:
  pull_request:
    types:
      - "opened"
      - "edited"
      - "synchronize"

jobs:
  integration_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chart/kepler
    strategy:
      matrix:
        kube_provider: [kind]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: use kepler action for kind cluster build
        uses: sustainable-computing-io/kepler-action@main
        with:
          runningBranch: kind

      - name: install helm
        run: |     
            curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
            sudo apt-get install apt-transport-https --yes
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
            sudo apt-get update
            sudo apt-get install helm
            sudo apt-get install tree

      - name: helm lint
        run: |
            helm lint . --debug

      - name: deploy kepler using helm chart
        run: |
            tree -a
            helm install  kepler . --values values.yaml  --create-namespace  --namespace kepler --dry-run --debug
            helm install  kepler . --values values.yaml  --create-namespace  --namespace kepler --debug

      - name: test if kepler is alive
        run: |
          sleep 60
          kubectl logs $(kubectl -n kepler get pods -oname) -n kepler
          kubectl get all -n kepler
